spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.payflow.notificationservice.domain.event.PaymentNotificationEvent

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always