### Ödeme başlat
POST http://localhost:8082/api/payments
Content-Type: application/json

{
  "sourceAccountId": "3519a8df-3162-40ce-a66c-e570b571a29e",
  "targetAccountId": "7bbf7848-0022-4a09-8e60-417aeffb8adb",
  "amount": 100.00,
  "currency": "TRY",
  "description": "Test ödemesi"
}


###

### Ödeme başlat — iyzico üzerinden
POST http://localhost:8082/api/payments
Content-Type: application/json

{
  "sourceAccountId": "968a2808-2068-4160-bf92-de7b92b7816f",
  "targetAccountId": "b8e9d810-342e-4e06-818f-e6b29d729e70",
  "amount": 15.00,
  "currency": "TRY",
  "description": "iyzico test ödemesi",
  "cardDetails": {
    "cardHolderName": "Test User",
    "cardNumber": "5528790000000008",
    "expireMonth": "12",
    "expireYear": "2030",
    "cvc": "123"
  },
  "buyerDetails": {
    "buyerId": "user-123",
    "name": "Ahmet",
    "surname": "Yılmaz",
    "email": "ahmet@test.com"
  }
}

### Ödeme getir
GET http://localhost:8082/api/payments/0fee40d0-d4e1-43ce-af56-9748733e834d


### Ödeme durumu — COMPLETED olmalı
GET http://localhost:8082/api/payments/0fee40d0-d4e1-43ce-af56-9748733e834d

### Bakiye — 500 azalmış olmalı
GET http://localhost:8081/api/accounts/3519a8df-3162-40ce-a66c-e570b571a29e/balance