### Hesap oluştur
POST http://localhost:8081/api/accounts
Content-Type: application/json

{
  "ownerId": "user-2",
  "currency": "TRY",
  "initialDeposit": 1000.00
}

###

### Hesap getir — yukarıdaki id'yi koy
GET http://localhost:8081/api/accounts/968a2808-2068-4160-bf92-de7b92b7816f

###

### Bakiye sorgula
GET http://localhost:8081/api/accounts/b4136f51-1d6b-42b1-8b5d-e9338c4642a3/balance

###

### Para yatır
POST http://localhost:8081/api/accounts/7bbf7848-0022-4a09-8e60-417aeffb8adb/deposit
Content-Type: application/json

{
  "amount": 500.00,
  "currency": "TRY",
  "description": "Maaş"
}

###

### Para çek
POST http://localhost:8081/api/accounts/7bbf7848-0022-4a09-8e60-417aeffb8adb/withdraw
Content-Type: application/json

{
  "amount": 1300.00,
  "currency": "TRY",
  "description": "Market"
}

###

### Yetersiz bakiye testi — 422 dönmeli
POST http://localhost:8081/api/accounts/7bbf7848-0022-4a09-8e60-417aeffb8adb/withdraw
Content-Type: application/json

{
  "amount": 999999.00,
  "currency": "TRY",
  "description": "Çok fazla"
}

###

### Askıya al
PATCH http://localhost:8081/api/accounts/7bbf7848-0022-4a09-8e60-417aeffb8adb/suspend?reason=Şüpheli işlem

###

### Askıdaki hesaba para çek — 403 dönmeli
POST http://localhost:8081/api/accounts/7bbf7848-0022-4a09-8e60-417aeffb8adb/withdraw
Content-Type: application/json

{
  "amount": 100.00,
  "currency": "TRY",
  "description": "Test"
}

###

### Yeniden aktif et
PATCH http://localhost:8081/api/accounts/7bbf7848-0022-4a09-8e60-417aeffb8adb/reactivate

###

### Hesabı kapat (önce bakiyeyi sıfırla)
PATCH http://localhost:8081/api/accounts/7bbf7848-0022-4a09-8e60-417aeffb8adb/close?reason=Kullanıcı talebi